#ifndef CONFIG_H_
#define CONFIG_H_

#define ENCODER_VALUE TIM5->CNT
#define CONTROLLERLOOPTIME_FLOAT 0.02f
#define CONTROLLERLOOPTIME_MS 20
#define CONTROLLERLOOPTIME_FREQ 50

#endif /* CONFIG_H_ */
